### PR TITLE
chore: ignore .vscode config folder

### PR DESCRIPTION
**Pull request by rahmatrhd**

### CODE REVIEW

**Comment by ravisuhag** [comment]
@rahmatrhd I would suggest avoiding putting it in VCS. We should leave this up to devs based on which editor they use.

**Comment by rahmatrhd** [comment]
@ravisuhag understood that this is vscode specific, was thinking to share this "recommended configuration" for devs who use vscode, otherwise, they can just ignore it. That's why I only allow `launch.json` file in the .gitignore. What do you think?

**Comment by StewartJingga** [comment]
I'd have to agree with @ravisuhag on this, this is way too specific and the value gained is not that significant.
And you will need keep checking and sync the `launch.json` to make sure it is still relevant for any updates.

**Comment by rahmatrhd** [comment]
Understood, will ignore the whole .vscode then

**Pull request merged**
