### PR TITLE
fix: optimize list approvals query

### LINKED ISSUE #231: optimize list approvals query
**Description**
The list approvals query is unoptimized and runs for far too long for some users due to them being approval owners for a good chunk of resources. 

sample log line:
```
2022/07/27 07:59:25 /home/runner/work/guardian/guardian/internal/store/postgres/approval_repository.go:69 SLOW SQL >= 200ms
[330.108ms] [rows:3739] SELECT "approvals"."id","approvals"."name","approvals"."index","approvals"."appeal_id","approvals"."status","approvals"."actor","approvals"."reason","approvals"."policy_id","approvals"."policy_version","approvals"."created_at","approvals"."updated_at","approvals"."deleted_at","Appeal"."id" AS "Appeal__id","Appeal"."resource_id" AS "Appeal__resource_id","Appeal"."policy_id" AS "Appeal__policy_id","Appeal"."policy_version" AS "Appeal__policy_version","Appeal"."status" AS "Appeal__status","Appeal"."account_id" AS "Appeal__account_id","Appeal"."account_type" AS "Appeal__account_type","Appeal"."created_by" AS "Appeal__created_by","Appeal"."creator" AS "Appeal__creator","Appeal"."role" AS "Appeal__role","Appeal"."options" AS "Appeal__options","Appeal"."labels" AS "Appeal__labels","Appeal"."details" AS "Appeal__details","Appeal"."revoked_by" AS "Appeal__revoked_by","Appeal"."revoked_at" AS "Appeal__revoked_at","Appeal"."revoke_reason" AS "Appeal__revoke_reason","Appeal"."created_at" AS "Appeal__created_at","Appeal"."updated_at" AS "Appeal__updated_at","Appeal"."deleted_at" AS "Appeal__deleted_at" FROM "approvals" LEFT JOIN "appeals" "Appeal" ON "approvals"."appeal_id" = "Appeal"."id" 
WHERE "approvals"."status" IN ('0','approved','1','rejected','2','pending') 
AND "Appeal"."status" != 'canceled' 
AND "approvals"."id" IN ('approval_id_1', ... a couple of thousand id records)
AND "approvals"."deleted_at" IS NULL
```

The main reason this runs slow is due to the way the query is structured in [here](https://github.com/odpf/guardian/blob/main/internal/store/postgres/approval_repository.go#L69). 
* First the list of `approval_ids` is fetched from the `approvers` table with email filter into code.
* This approval_id list is used to fetch approvals from the approvals table using an `in` query.

Instead, one can join the `approvers` table with `approvals` and get the approval records directly from DB itself.

### PR DESCRIPTION
**Pull request by bsushmith**
* Instead of fetching approvers first and using a `in` query to fetch approvals, join approvers with approvals table to remove the `in` clause

closes #231

### CODE REVIEW

**Review by singhvikash11 — APPROVED** [review]

**Comment by mabdh** [comment]
Seeing the code, I think it will be much more readable if we just use non-gorm way. 
I am just wondering, with our current evolved use cases, do we really need GORM? or can we just use get rid of ORM and just build query using some library like squirrel or goqu?

**Review by rahmatrhd — APPROVED** [review]
code LGTM, please resolve the conflict

**Comment by rahmatrhd** [comment]
@mabdh we can start an issue for that

**Comment by bsushmith** [comment]
resolved conflicts. @rahmatrhd 👍

**Pull request merged**
