### PR TITLE
docs: update documentation

### PR DESCRIPTION
**Pull request by Chief-Rishab**
- [ ] Documentation for the Provider plugins
     - [x] Add No-Op Provider
     - [x] Update BigQuery
     - [ ] Update Metabase
     - [x] Update GCS
     - [ ] Update Grafana
     - [x] Update GCloud IAM
- [x] Add Server Jobs Reference 
- [x] Add descriptions with examples on the API reference page
- [x] Update Introduction

### CODE REVIEW

**Comment by mabdh** [comment]
@Chief-Rishab this has been stale for a long time, any progress for this?

**Comment by mabdh** [comment]
@ravisuhag the more feature we develop the more likely for a doc of one of this component to be irrelevant. Should we split this documentation into several issues instead?
cc @rahmatrhd @Chief-Rishab

**Comment by Chief-Rishab** [comment]
@mabdh yes, we can do one thing. I will complete the docs for provider plugins which are the first in the list of to-do's in the description and merge in the main branch. After that we can go and add the new branches for the development guide, and architecture separately since it might be a larger story altogether and add to main branch as we complete

**Comment by mabdh** [comment]
@Chief-Rishab thank you! can you please also create separate issues for the rest 🙏🏼  ?

**Comment by Chief-Rishab** [comment]
@abduh created three issues for updating the documentation. Will complete this and mark for review

**Comment by ravisuhag** [comment]
@Chief-Rishab I am merging this PR to unblock folks on updating other parts of docs. You can raise another PR for pending things on docs from your side.

**Pull request merged**
