### PR TITLE
fix: add blank as default value for IAM schema

### PR DESCRIPTION
**Pull request by singhvikash11**

### CODE REVIEW

**Comment by singhvikash11** [comment]
### What

> Add blank string as default for IAM schema provider attributes

### Why

> Issue with [expr](https://github.com/antonmedv/expr) library, it's not able to evaluate the following expression:
`($appeal.creator.product_group != nil && $appeal.creator.supervisory_org != nil) && $appeal.creator.product_group contains 'Financial Services' || $appeal.creator.product_group contains 'financial services' || (($appeal.creator.product_group. == 'Not Applicable' || $appeal.creator.product_group == 'not applicable') && ($appeal.creator.supervisory_org contains 'Financial Services' || $appeal.creator.supervisory_org contains 'financial services'))`

Here [expr](https://github.com/antonmedv/expr) library trying to evaluate the contains operator though there is an **and operator** before this and **it should break the circuit**.

https://github.com/antonmedv/expr/blob/master/vm/vm.go#L248

**Comment by rahmatrhd** [comment]
@singhvikash11  have you tried adding `$appeal.creator != nil` at the beginning?

**Comment by singhvikash11** [comment]
@rahmatrhd we add a nil check-in policy file at the beginning but the given library implement stack to evaluate an expression. It does not break the circuit even condition evaluate as false.

**Comment by rahmatrhd** [comment]
@singhvikash11 can you help to re-check your usecase again using this expression:
```
$appeal.creator != nil && $appeal.creator.product_group != nil && $appeal.creator.supervisory_org != nil && ($appeal.creator.product_group contains 'Financial Services' || $appeal.creator.product_group contains 'financial services' || (($appeal.creator.product_group == 'Not Applicable' || $appeal.creator.product_group == 'not applicable') && ($appeal.creator.supervisory_org contains 'Financial Services' || $appeal.creator.supervisory_org contains 'financial services')))
```

I also added a similar test case here https://github.com/odpf/guardian/pull/163

**Pull request merged**
