### PR TITLE
feat: update missing cli features

### PR DESCRIPTION
**Pull request by ishanarya0**
Missing features to add in CLI:

- [x] account_type flag in appeals create command
- [x] command for showing the approval statuses (visualization)
- [x] resource get metadata cmd
- [x] appeal revoke
- [x] appeal cancel

### CODE REVIEW

**Comment by ishanarya0** [comment]
Added command to see the status of all the approvals of an appeal.

Command:
`guardian appeal status --id=<appeal-id>`

Output:
```
Showing 3 approval steps
 
ID      NAME            STATUS          APPROVER                ACTOR          
1       owner_approval  approved        ishan@gojek.com         ishan@gojek.com
2       boss_Approval   pending         akshat@gojek.com                       
3       vip_Approval    blocked         sanjay@gojek.com 
```

@rahmatrhd @ravisuhag do we want to see any other information in the output table?

**Comment by rahmatrhd** [comment]
1. can we also show the appeal status before printing the approvals table? Maybe something like this: `Appeal status: pending`
2. suggesting to change the approver column name to `APPROVER(s)`
3. if the status is approved, we can show the status text to `Approved by <actor>`, same thing for status rejected. And we can remove showing `ACTOR` column

**Comment by ishanarya0** [comment]
Added metadata get command.

Command: `guardian metadata-get --id=<resource-id>`

Output:

1. No metadata

`This resource has no metadata to show.`

2. Has metadata

```
DETAILS

foo : bar
key : a value
nested : [map[color:red value:#f00]]
bar : foo
```

**Comment by ishanarya0** [comment]
Changed metadata set command.

Command: `guardian metadata-set --id=<resource-id> --values foo=bar`

**Comment by ravisuhag** [comment]
> Changed metadata set command.
> 
> Command: `guardian metadata-set --id=<resource-id> --values foo=bar`

I think we should have just `view` and `set` commands on resource.  `view` should show all data related to resource including metadata. The format of view can be configured with a flag. Similarly `set` should allow to update the fields of resources including metadata.

**Comment by ishanarya0** [comment]
> > Changed metadata set command.
> > Command: `guardian metadata-set --id=<resource-id> --values foo=bar`
> 
> I think we should have just `view` and `set` commands on resource. `view` should show all data related to resource including metadata. The format of view can be configured with a flag. Similarly `set` should allow to update the fields of resources including metadata.

Yes, that would be a better approach.

**Comment by ishanarya0** [comment]
> > Changed metadata set command.
> > Command: `guardian metadata-set --id=<resource-id> --values foo=bar`
> 
> I think we should have just `view` and `set` commands on resource. `view` should show all data related to resource including metadata. The format of view can be configured with a flag. Similarly `set` should allow to update the fields of resources including metadata.

@ravisuhag  Shall we only take a file path input in the set command, to update all the fields including metadata, or, give a separate flag for metadata?

`guardian set --id=1 --filepath=<path>`

OR

`guardian set --id=1 --filepath=<path> --metadata <array of key value pairs>`

**Comment by ishanarya0** [comment]
This is ready for review @rahmatrhd @ravisuhag

**Pull request merged**
