### PR TITLE
fix: make notification as local variable

### LINKED ISSUE #329: Getting 3 times slack notification for same resource reminder
**Description**
For the same resource expiration guardian send 3 times notification, I am guessing the reordering of var notifications can cause issues.

image

### PR DESCRIPTION
**Pull request by singhvikash11**
fix #329

### CODE REVIEW

**Comment by mabdh** [comment]
Have we tested this? Or could we test this flow to make sure this is a correct solution?

**Comment by mabdh** [comment]
This should be a `fix` instead a `chore` right?

**Comment by rahmatrhd** [comment]
can you also share how this changes could fix the issue? wanted to know why the previous code causing the issue 🙏

**Comment by bsushmith** [comment]
This PR is no longer needed.

**Comment by ravisuhag** [comment]
@bsushmith Is the issue #329 solved in another PR or that still remains open? cc @rahmatrhd

**Comment by bsushmith** [comment]
@ravisuhag It is still open - We haven't aligned on when we want to deprecate the older configs (which were present for backward compatibility)
comment - https://github.com/odpf/guardian/issues/329#issuecomment-1321448049

**Pull request closed without merging**
